version = 1
schema = "prdoc/schema_user.json"
output_dir = "prdoc"
prdoc_folders = ["prdoc"]
template = "templates/prdoc/.template.prdoc"

[audiences]
developer = "Developer"
user = "User"
operator = "Operator"